#!/usr/bin/env node
/* Rebuilds js/textures_data.js — base64 data-URIs of every texture file.
 *
 * Why embedded: Chrome taints images loaded from a file:// page origin and
 * WebGL refuses to upload them (SecurityError from texImage2D). Data-URI
 * images are same-origin and upload cleanly, so the app runs fully from a
 * double-click on index.html with no local server.
 *
 * Run this after swapping ANY file in textures/ :
 *   node tools/embed_textures.js
 */
"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const TEX_FILES = [
  "sun.jpg", "mercury.jpg", "venus.jpg", "earth.jpg", "earth_clouds.jpg",
  "earth_night.jpg", "mars.jpg", "jupiter.jpg", "saturn.jpg", "saturn_ring.png",
  "uranus.jpg", "neptune.jpg", "moon.jpg", "pluto.jpg", "stars_milky_way.jpg"
];
const MIME = { ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png" };

const lines = [];
lines.push("/* AUTO-GENERATED by tools/embed_textures.js - do not edit by hand. */");
lines.push("/*");
lines.push(" * Base64 data-URIs of the texture set. Chrome taints images loaded");
lines.push(" * from a file:// page origin and WebGL refuses to upload them, so");
lines.push(" * the textures are embedded: data: URLs are same-origin and the app");
lines.push(" * runs fully from a double-click on index.html (no local server).");
lines.push(" *");
lines.push(" * After swapping any file in textures/, regenerate with:");
lines.push(" *   node tools/embed_textures.js");
lines.push(" */");
lines.push("window.SIM_TEXTURES = {");

TEX_FILES.forEach(function (f, i) {
  const p = path.join(ROOT, "textures", f);
  if (!fs.existsSync(p)) {
    console.error("MISSING texture file: " + p);
    process.exit(1);
  }
  const b64 = fs.readFileSync(p).toString("base64");
  const mime = MIME[path.extname(f).toLowerCase()] || "application/octet-stream";
  console.log("  embedded " + f + "  (" + (b64.length / 1e6).toFixed(1) + " MB base64)");
  lines.push("  " + JSON.stringify(f) + ": " + JSON.stringify("data:" + mime + ";base64," + b64) + (i < TEX_FILES.length - 1 ? "," : ""));
});
lines.push("};");

const outPath = path.join(ROOT, "js", "textures_data.js");
fs.writeFileSync(outPath, lines.join("\n"));
console.log("wrote " + path.relative(ROOT, outPath) + "  (" + (fs.statSync(outPath).size / 1e6).toFixed(1) + " MB)");
